version: "3.9"

services:
  platform:
    image: wind_forecast
    container_name: wind_forecast
    network_mode: ${NETWORK_MODE}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        PATH_TO_SCRIPT: ${PATH_TO_SCRIPT}
        MAIN_DIR: ${MAIN_DIR}
        GENERAL_BRANCH: ${GENERAL_BRANCH}
        GIT_SSL_NO_VERIFY: ${GIT_SSL_NO_VERIFY}
        GIT_TOKEN: ${GIT_TOKEN}
        GIT_HOST: ${GIT_HOST}
        GIT_URN: ${GIT_URN}
        LOG_PATH: ${LOG_PATH}
        LOG_FILE: ${LOG_FILE}
    restart: on-failure
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

networks:
  default:
    external:
      name: ${NETWORK_MODE}
