version: "3.9"

services:
  platform:
    image: consumption_forecast
    container_name: consumption_forecast
    network_mode: ${NETWORK_MODE}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        PATH_TO_SCRIPT: ${PATH_TO_SCRIPT}
        MAIN_DIR: ${MAIN_DIR}
        GENERAL_BRANCH: ${GENERAL_BRANCH}
        GIT_SSL_NO_VERIFY: ${GIT_SSL_NO_VERIFY}
        GIT_TOKEN: ${GIT_TOKEN}
        GIT_HOST: ${GIT_HOST}
        GIT_URN: ${GIT_URN}
        LOG_PATH: ${LOG_PATH}
        LOG_FILE: ${LOG_FILE}
        STORAGE_PATH: ${STORAGE_PATH}
        STORAGE: ${STORAGE}
    volumes:
      - storage:${STORAGE}
    restart: on-failure
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

volumes:
  storage:
    name: ${VOLUME_NAME}
    driver: ${VOLUME_DRIVER}
    driver_opts:
      o: bind
      type: none
      device: /ecs${STORAGE}${VOLUME_DEVICE}

networks:
  default:
    external:
      name: ${NETWORK_MODE}
